version: '3.7'
services:
  app:
    image: olamideokunola/payments-ui
    ports:
      - 3000:3000
    working_dir: /payments-ui
    volumes:
      - ./:/payments-ui
    environment:
      REACT_APP_AUTHENTICATION_HOST: 165.232.84.196
      REACT_APP_BACKEND_SERVER_HOST: 165.232.84.196
      REACT_APP_INDEXING_SERVER_HOST: 178.62.231.110
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports: 
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  trading-app-be:
    image: olamideokunola/trading-app-be
    restart: always
    environment:
      DB_HOST: db
      PAYMENTS_UI_HOST: localhost
    ports:
      - 4000:4000
volumes:
  db: